jwt:
  access_token_expire_minutes: 1  # Время жизни токена доступа в минутах

encryption:
  # Возможные алгоритмы шифрования:
  # aes - Алгоритм AES (симметричное шифрование)
  # rsa - Алгоритм RSA (асимметричное шифрование)
  # chacha20 - Алгоритм ChaCha20 (современный потоковый шифратор)
  algorithm: aes  # Выбранный алгоритм шифрования (по умолчанию aes)

totp:
  totp_code_len: 6  # Длина кода TOTP
  totp_secret_len: 32  # Длина секрета TOTP
  totp_minimal_secret_len: 16  # Минимальная длина секрета TOTP

auth:
  max_login_attempts: 5
  block_duration_minutes: 15

logging:
  filename: lockana.log  # Имя файла для логов